[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 